title: "тележка эйай"
description: "Telegram-канал про вайб и про кодинг, про внедрение эйай, про хайп и про правду."
lang: ru
timezone: Europe/Moscow
url: "https://obey177.github.io"
baseurl: "/telezkaai"
markdown: kramdown
permalink: /posts/:title/
future: false

channel_title: "тележка эйай"
channel_subtitle: "AI, IT и корпоративная тревога на колёсах"
telegram_url: "https://t.me/telezkaai"
logo: /assets/images/telezkaai-logo.webp
